# Imagem base com Node (Angular CLI exige Node.js)
FROM node:20

# Define diretório de trabalho
WORKDIR /app

# Copia arquivos package.json e package-lock.json
COPY package*.json ./

# Instala dependências
RUN npm install -g @angular/cli && npm install

# Copia o restante do projeto Angular
COPY . .

# Expõe a porta padrão do ng serve
EXPOSE 4200

# Comando para iniciar o servidor Angular
CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]


